INSERT INTO RESTAURANT (CODE, CATEGORY, NAME, ADDRESS, PHONE_NUMBER)
VALUES ('R001', 'Italian', 'The Pasta Place', '123 Spaghetti Blvd', '555-1234'),
       ('R002', 'French', 'Le Gourmet', '234 Bistro St', '555-2345'),
       ('R003', 'American', 'Burger Barn', '345 Diner Dr', '555-3456'),
       ('R004', 'Mexican', 'Taco Town', '456 Fajita Rd', '555-4567'),
       ('R005', 'Japanese', 'Sushi Spot', '567 Sashimi Way', '555-5678'),
       ('R006', 'Chinese', 'Dragon Delight', '678 Wonton Ln', '555-6789'),
       ('R007', 'Indian', 'Curry Corner', '789 Masala Ave', '555-7890'),
       ('R008', 'Thai', 'Thai Terrace', '890 Pad Thai Pl', '555-8901'),
       ('R009', 'Mediterranean', 'Mediterra', '901 Hummus Hl', '555-9012'),
       ('R010', 'Vegetarian', 'Veggie Vault', '123 Leafy Ln', '555-0123'),
       ('R011', 'Vegan', 'Green Garden', '234 Plant Pl', '555-0234'),
       ('R012', 'Barbecue', 'BBQ Base', '345 Smoky Sq', '555-0345'),
       ('R013', 'Seafood', 'Sea Breeze', '456 Oceanic Oc', '555-0456'),
       ('R014', 'Steakhouse', 'Steak Central', '567 T-Bone Tr', '555-0567'),
       ('R015', 'Cafe', 'Caffeine Cafe', '678 Brew Blvd', '555-0678');


INSERT INTO FOOD (CODE, NAME, DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES
    ('F01', 'Margherita Pizza', 'Classic pizza with tomato sauce and mozzarella cheese', 9.99, 1),
    ('F02', 'Pepperoni Pizza', 'Pepperoni with mozzarella and tomato sauce', 10.99, 1),
    ('F03', 'Veggie Burger', 'A delicious vegetarian burger patty with lettuce, tomato, and sauce', 8.50, 1),
    ('F04', 'Chicken Caesar Salad', 'Grilled chicken, romaine, croutons, Parmesan, and Caesar dressing', 7.50, 1),
    ('F05', 'Spaghetti Carbonara', 'Spaghetti with creamy sauce, bacon, and Parmesan cheese', 11.00, 1),
    ('F06', 'Beef Taco', 'Ground beef, cheese, lettuce, and tomato in a crunchy taco shell', 3.00, 1),
    ('F07', 'Chicken Burrito', 'Grilled chicken, rice, beans, cheese, and salsa wrapped in a tortilla', 7.25, 1),
    ('F08', 'Sushi Roll', 'Fresh salmon, avocado, and cucumber wrapped in seaweed and rice', 8.95, 1),
    ('F09', 'Pad Thai', 'Stir-fried rice noodles with shrimp, peanuts, egg, and bean sprouts', 9.50, 1),
    ('F10', 'Falafel Wrap', 'Falafel balls, lettuce, tomato, and tahini sauce wrapped in a flatbread', 6.99, 1),
    ('F11', 'Lamb Gyro', 'Slices of lamb, tzatziki sauce, lettuce, and tomato in a pita bread', 7.95, 1),
    ('F12', 'Mushroom Risotto', 'Creamy risotto with wild mushrooms and Parmesan cheese', 10.50, 1),
    ('F13', 'Fried Chicken', 'Crispy fried chicken served with a side of mashed potatoes', 9.25, 1),
    ('F14', 'Ribeye Steak', 'Grilled ribeye steak with a side of vegetables', 22.00, 1),
    ('F15', 'Pork Dumplings', 'Pork-filled dumplings served with soy sauce', 5.95, 1),
    ('F16', 'Vegetable Stir Fry', 'Mixed vegetables stir-fried with a soy-based sauce', 8.25, 1),
    ('F17', 'Fish and Chips', 'Fried fish served with a side of chips', 10.00, 1),
    ('F18', 'BBQ Ribs', 'Slow-cooked ribs covered in BBQ sauce', 15.50, 1),
    ('F19', 'Caesar Salad', 'Romaine, croutons, Parmesan, and Caesar dressing', 5.50, 1),
    ('F20', 'Cheeseburger', 'Burger with cheese, lettuce, tomato, and onion on a bun', 9.00, 1);
