DROP TABLE IF EXISTS USER_FAVORITES CASCADE;
DROP TABLE IF EXISTS REVIEWS CASCADE;
DROP TABLE IF EXISTS FOOD CASCADE;
DROP TABLE IF EXISTS RESTAURANTS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS
(
    USER_ID  INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE RESTAURANT
(
    RESTAURANT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE          VARCHAR(255) NOT NULL UNIQUE,
    CATEGORY      VARCHAR(255),
    NAME          VARCHAR(255) NOT NULL,
    ADDRESS       VARCHAR(255),
    PHONE_NUMBER  VARCHAR(255)
);

CREATE TABLE FOOD
(
    FOOD_ID       INT AUTO_INCREMENT PRIMARY KEY,
    CODE          VARCHAR(255) NOT NULL UNIQUE,
    NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION   VARCHAR(255),
    PRICE         DECIMAL(10, 2),
    RESTAURANT_ID INT,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID)
);

CREATE TABLE USER_FAVORITES
(
    USER_ID INT,
    FOOD_ID INT,
    PRIMARY KEY (USER_ID, FOOD_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID)
);

CREATE TABLE REVIEWS
(
    REVIEW_ID     INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID       INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    RATING        INT CHECK (RATING >= 1 AND RATING <= 5),
    COMMENT       TEXT,
    REVIEW_DATE   DATE,
    UNIQUE (USER_ID, RESTAURANT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID)
);
